name = "learnings-api"
main = "src/index.ts"
compatibility_date = "2025-09-01"

[dev]
port = 8787

[vars]
CORS_ORIGIN = "*" # set to prod origin later
JWT_SECRET = "learnings-jwt-secret-change-in-production-2025"
LINKEDIN_CLIENT_ID = "REPLACE_WITH_LINKEDIN_CLIENT_ID"
LINKEDIN_CLIENT_SECRET = "REPLACE_WITH_LINKEDIN_CLIENT_SECRET"

[[d1_databases]]
binding = "DB"
database_name = "learnings"
database_id = "af30f5a0-193d-464f-8019-b82c71bdcfb5"

[[r2_buckets]]
binding = "R2"
bucket_name = "learnings-assets"

[[kv_namespaces]]
binding = "CACHE"
id = "5c2b6e7727ec4a0bb520e720e8e35eae"

[[kv_namespaces]]
binding = "BUZZWORD_RATELIMIT"
id = "d3a16d219adf453eaa361cb929c37426"

[[queues.producers]]
binding = "JOBS"
queue = "learnings-jobs"

[[queues.consumers]]
binding = "JOBS"
queue = "learnings-jobs"
script_name = "learnings-api"

[ai]
binding = "AI"

[triggers]
crons = ["0 9 * * 1"] # Every Monday at 9 AM UTC
