name = "learnings-api"
main = "src/index.ts"
compatibility_date = "2025-09-01"

[vars]
CORS_ORIGIN = "*" # set to prod origin later

[[d1_databases]]
binding = "DB"
database_name = "learnings_db"
database_id = "REPLACE_WITH_D1_ID"

[[r2_buckets]]
binding = "R2"
bucket_name = "learnings-assets"

[[kv_namespaces]]
binding = "CACHE"
id = "REPLACE_WITH_KV_ID"

[[queues.producers]]
binding = "JOBS"
queue = "learnings-jobs"

[[vectorize]]
binding = "VEC"
index_name = "learnings-terms"

[ai]
binding = "AI"
